# Permalinks
permalink:           pretty


# Setup
title:               Sumil Thakrar
tagline:             Environmental Scientist
url:                 https://sumil.me
#paginate:            5
baseurl:             ""
permalink:          /:title.html

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Google Analytics
google_analytics: G-GW8CQGDNXE

# About/contact
author:
  name:              Sumil Thakrar
  url:               https://www.wikidata.org/wiki/Q92282874

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
